this?

diff --git a/overlay/usr/local/etc/rc.d/homeassistant b/overlay/usr/local/etc/rc.d/homeassistant
--- a/overlay/usr/local/etc/rc.d/homeassistant
+++ b/overlay/usr/local/etc/rc.d/homeassistant
@@ -251,17 +251,17 @@ homeassistant_install() {
   su - ${homeassistant_user} -c '
     if [ ${1} == "YES" ]; then
       ${2} -m venv ${3}
-      source ${3}/bin/activate || exit 1
+      source ${3}/bin/activate || exit 5
       shift 3
-      pip install wheel
-      pip install ${@}
+      pip3 install wheel
+      pip3 install ${@}
     else
       source ${3}/bin/activate || exit 1
       shift 3
       pip install ${@}
     fi
     deactivate
-  ' _ ${_create_:-"NO"} ${homeassistant_python} ${homeassistant_venv} "${_arg_}" || err 1 "install function failed"
+  ' _ ${_create_:-"NO"} ${homeassistant_python} ${homeassistant_venv} "${_arg_}" || err 1 "exit: $? - install function failed"
 }
 
 reinstall_cmd="${name}_reinstall ${*}"
